// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs _fsmap_defs_linux.go

package fsmap

const FS_IOC_GETFSMAP = 0xc0c0583b
const FMR_OWN_FREE = 0x1

const FMR_OF_SPECIAL_OWNER = 0x10
const FMR_OF_LAST = 0x20

type FSMap struct {
	Device   uint32
	Flags    uint32
	Physical uint64
	Owner    uint64
	Offset   uint64
	Length   uint64
	Reserved [3]uint64
}
type FSMapHead struct {
	Iflags   uint32
	Oflags   uint32
	Count    uint32
	Entries  uint32
	Reserved [6]uint64
	Keys     [2]FSMap
}

const Sizeof_FSMap = 0x40
const Sizeof_FSMapHead = 0xc0
const FSMapEntries = 1024
const Sizeof_FSMapEntries = Sizeof_FSMapHead + FSMapEntries*Sizeof_FSMapHead
